import os
import yaml
from pydantic import ValidationError
from schema import Obligation

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    yaml_path = os.path.join(base_dir, "src", "obligations.yaml")
    review_path = os.path.join(base_dir, "OBLIGATIONS_REVIEW.md")

    print(f"Loading obligations from: {yaml_path}")
    if not os.path.exists(yaml_path):
        print("Error: obligations.yaml file not found!")
        exit(1)

    with open(yaml_path, "r", encoding="utf-8") as f:
        try:
            data = yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"YAML Parsing Error: {e}")
            exit(1)

    if not data or "obligations" not in data:
        print("Error: No 'obligations' key found in YAML!")
        exit(1)

    obligations_list = data["obligations"]
    print(f"Found {len(obligations_list)} obligation entries. Validating...")

    validated_obligations = []
    errors = 0

    for idx, item in enumerate(obligations_list):
        try:
            obl = Obligation(**item)
            validated_obligations.append(obl)
        except ValidationError as e:
            print(f"\n[ERROR] Entry {idx} (ID: {item.get('id', 'UNKNOWN')}) failed validation:")
            print(e)
            errors += 1

    if errors > 0:
        print(f"\nValidation failed with {errors} errors.")
        exit(1)

    print("All obligations validated successfully against the schema!")

    print(f"Generating review report at: {review_path}")
    with open(review_path, "w", encoding="utf-8") as f:
        f.write("# DPDPA Obligations Review Report (Ground Truth)\n\n")
        f.write("This document is auto-generated by the validation script. **Please review these obligation definitions against the actual text of the Digital Personal Data Protection Act, 2023.**\n\n")
        
        f.write("## Summary Statistics\n")
        f.write(f"- **Total Obligations Indexed**: {len(validated_obligations)}\n")
        f.write("- **Schema Compliance**: Verified against Pydantic V2\n\n")
        
        f.write("## Obligations Database\n\n")
        
        for o in validated_obligations:
            f.write(f"### {o.section_citation} — `{o.id}`\n\n")
            f.write(f"- **Chapter**: {o.chapter}\n")
            f.write(f"- **Core Obligation Text**: {o.obligation_text}\n")
            f.write("- **Applicability Conditions**:\n")
            for k, v in o.applicability_conditions.items():
                f.write(f"  - `{k}`: `{v}`\n")
            
            f.write("- **Evidence Checklist**:\n")
            for item in o.evidence_checklist:
                f.write(f"  - [ ] {item.item}\n")
                f.write(f"    - *Positive Keywords*: `{item.positive_keywords}`\n")
                if item.negative_keywords:
                    f.write(f"    - *Negative/Negation Keywords*: `{item.negative_keywords}`\n")
                
            if o.exemption_refs:
                f.write(f"- **Applicable Exemptions**: {', '.join(o.exemption_refs)}\n")
            else:
                f.write("- **Applicable Exemptions**: None (Non-exempt obligations like security safeguards and compliance responsibility)\n")
                
            if o.penalty_ref:
                f.write(f"- **Penalty Reference**: {o.penalty_ref}\n")
            else:
                f.write("- **Penalty Reference**: None specified\n")
                
            f.write(f"- **Version**: {o.version}\n")
            f.write("\n---\n\n")

    print("Review report generated successfully.")

if __name__ == "__main__":
    main()
